In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [50]:
dataset = pd.read_csv("corona.csv")

In [52]:
dataset.value_counts()

fever       bodypain  age  runnyNose  diffBreath  probability
98.000664   0         44   0          -1          1              1
100.686553  1         64   0           1          1              1
100.684460  1         90   1           1          0              1
100.680254  1         80   0           0          1              1
100.676149  0         37   1          -1          0              1
                                                                ..
99.319515   1         79   1          -1          0              1
99.319235   1         21   1           1          1              1
99.317454   0         82   1           1          1              1
99.316197   1         41   1           0          1              1
101.997881  0         40   1          -1          1              1
Name: count, Length: 2106, dtype: int64

In [54]:
dataset.shape


(2106, 6)

In [55]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2106 entries, 0 to 2105
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   fever        2106 non-null   float64
 1   bodypain     2106 non-null   int64  
 2   age          2106 non-null   int64  
 3   runnyNose    2106 non-null   int64  
 4   diffBreath   2106 non-null   int64  
 5   probability  2106 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 98.8 KB


In [56]:
X =dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [57]:
from sklearn.model_selection import train_test_split
X_train ,X_test , y_train ,y_test = train_test_split(X ,y, test_size = 0.2 , random_state =0)

In [58]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test =sc.transform(X_test)

In [72]:
X_train[0]

array([ 0.9169039 , -1.01676764,  1.32043585, -0.99881306, -0.01592209])

In [73]:
y_train

array([1, 0, 1, ..., 1, 1, 0])

In [74]:
from sklearn.svm import SVC
LE = SVC(kernel = 'linear', random_state = 0)
LE.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [75]:
yPred = LE.predict(X_test)

In [ ]:
y_pred = LE.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [77]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[107  98]
 [126  91]]


0.46919431279620855